default: &default
  adapter: postgresql
  # ... other common settings

development:
  <<: *default
  database: ror_weather_app_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: ror_weather_app_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>


production:
  primary: &primary_production
    <<: *default
    database: weather_app_rails_production
    username: weather_app_rails
    password: <%= ENV["WEATHER_APP_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: weather_app_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: weather_app_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: weather_app_rails_production_cable
    migrations_paths: db/cable_migrate
